int counter = 0;
long rand1;
long rand2;
long rand3;
long rand4;
long rand5;
int right = 9; //If you get the sequence right
int wrong = 8; //If you get the sequence wrong
int blue = 11; //The first light that may be part of the sequence
int green = 12; //The second light that may be part of the sequence
int gbutt = 4; //The button that reads a click corresponding to the green light
int bbutt = 2; //The button that reads a click corresponding to the blue light
int gval = 0; //Sets the initial read of the button to not be depressed
int bval = 0; //Sets the initial read of the button to not be depressed
int buzz = 12; //The piezo that makes the sound for the game
int inputArray[5];
boolean button[] = {2,4};
int conter = 0;
boolean ext = false;
void setup()  {
  pinMode(right,OUTPUT); //Sets the inputs to be the two buttons, the outputs all the lights and the piezo
  pinMode(wrong,OUTPUT);
  pinMode(blue,OUTPUT);
  pinMode(green,OUTPUT);
  pinMode(button[2], INPUT);
  pinMode(button[4], INPUT);
  digitalWrite(button[2],HIGH);
  digitalWrite(button[4],HIGH);
  randomSeed(analogRead(0));
  

//This order will be generated by the player clicking the buttons in a certain order 
}  

void loop(){

  gval = digitalRead(button[4]);
  bval = digitalRead(button[2]);
    if (bval == LOW )  {
      digitalWrite(blue,HIGH);
    }
    else if(bval == HIGH) {
      digitalWrite(blue,LOW);
      
    }
    else {
      digitalWrite(green,HIGH);
      delay(1);
      digitalWrite(green,LOW);
      delay(1);
  }

}
  


